spring:
  application:
    name: hutu-ai
  #    AI配置
  ai:
    ollama:
      base-url: http://192.168.1.19:11434
      chat:
        model: deepseek-r1:7b
      embedding:
        model: nomic-embed-text
    vectorstore:
      pgvector:
        table-name: vector_store
        schema-name: public
        # 定义向量的维度数，必须与嵌入模型输出一致
        dimensions: 768
        # 指定向量相似度计算方式 cosine-distance:余弦相似度
        distance-type: cosine-distance
        # 若表不存在则自动创建
        initialize-schema: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${password}
    url: jdbc:postgresql://localhost:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1